// Generated by MavLink2AdHoc (https://github.com/AdHoc-Protocol) from standard.xml
// Sources, in emission order: minimal.xml, standard.xml
// MAVLink protocol version: 3
// MAVLink dialect number: 0
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.mavlink {
    /**
        <see cref = 'AUTOPILOT_VERSION'/>
        <see cref = 'GLOBAL_POSITION_INT'/>
        <see cref = 'HEARTBEAT'/>
    */
    public interface standard {

        // ═════════════════════════ elapsed-time aliases ═════════════════════════

        /** Time since system boot, millisecond resolution. MAVLink carries it as a uint32, which wraps after about 49.7 days. */
        class MillisecondsSinceBoot : Duration {
            public long     max       => uint.MaxValue;
            public TimeSpan precision => TimeSpan.FromMilliseconds(1);
        }


        // ═════════════════════════ messages of minimal.xml ═════════════════════════

        /**
        The heartbeat message shows that a system or component is present and responding. The type and autopilot
        fields (along with the message component id), allow the receiving system to treat further messages from this
        system appropriately (e.g. by laying out the user interface based on the autopilot). This microservice is
        documented at https://mavlink.io/en/services/heartbeat.html
        */
        class HEARTBEAT {
            public const int mavlink_message_id = 0;
            /**
            Vehicle or component type. For a flight controller component the vehicle type (quadrotor, helicopter, etc.).
            For other components the component type (e.g. camera, gimbal, etc.). This should be used in preference to
            component id for identifying the component type.
            */
            MAV_TYPE Type;
            /**
            Autopilot type / class. Use MAV_AUTOPILOT_INVALID for components that are not flight controllers.
            */
            MAV_AUTOPILOT autopilot;
            /**
            System mode bitmap.
            */
            MAV_MODE_FLAG base_mode;
            /**
            A bitfield for use for autopilot-specific flags
            */
            uint custom_mode;
            /**
            System status flag.
            */
            MAV_STATE system_status;
            /**
            MAVLink version, not writable by user, gets added by protocol because of magic data type:
            uint8_t_mavlink_version
            */
            byte mavlink_version;
        }

        // ═════════════════════════ messages of standard.xml ═════════════════════════

        /**
        The filtered global position (e.g. fused GPS and accelerometers). The position is in GPS-frame (right-handed,
        Z-up). It is designed as scaled integer message since the resolution of float is not sufficient.
        */
        class GLOBAL_POSITION_INT {
            public const int mavlink_message_id = 33;
            /**
            Timestamp (time since system boot).
            */
            [Units(SI_Unit.time.ms)] MillisecondsSinceBoot time_boot_ms;
            /**
            Latitude, expressed
            */
            // physics: scaled degrees, values around 5.6e8 - a varint attribute would COST a byte here
            [Units(SI_Unit.angle.degE7)] int lat;
            /**
            Longitude, expressed
            */
            // physics: scaled degrees, values around 5.6e8 - a varint attribute would COST a byte here
            [Units(SI_Unit.angle.degE7)] int lon;
            /**
            Altitude (MSL). Note that virtually all GPS modules provide both WGS84 and MSL.
            */
            // physics: small magnitude in a 32-bit field - consider [A] if never negative, [X] if it is
            [Units(SI_Unit.distance.mm)] int alt;
            /**
            Altitude above home
            */
            // physics: small magnitude in a 32-bit field - consider [A] if never negative, [X] if it is
            [Units(SI_Unit.distance.mm)] int relative_alt;
            /**
            Ground X Speed (Latitude, positive north)
            */
            // physics: rate or vector component, centred on zero - [X] would fit, though the type is already narrow
            [Units(SI_Unit.distance.cm_s)] short vx;
            /**
            Ground Y Speed (Longitude, positive east)
            */
            // physics: rate or vector component, centred on zero - [X] would fit, though the type is already narrow
            [Units(SI_Unit.distance.cm_s)] short vy;
            /**
            Ground Z Speed (Altitude, positive down)
            */
            // physics: rate or vector component, centred on zero - [X] would fit, though the type is already narrow
            [Units(SI_Unit.distance.cm_s)] short vz;
            /**
            Vehicle heading (yaw angle), 0.0..359.99 degrees. If unknown, set to: UINT16_MAX
            */
            [Units(SI_Unit.angle.cdeg), Invalid("UINT16_MAX")] ushort hdg;
        }

        /**
        Version and capability of autopilot software. This should be emitted in response to a request with
        MAV_CMD_REQUEST_MESSAGE.
        */
        class AUTOPILOT_VERSION {
            public const int mavlink_message_id = 148;
            /**
            Bitmap of capabilities
            */
            MAV_PROTOCOL_CAPABILITY capabilities;
            /**
            Firmware version number.
            The field must be encoded as 4 bytes, where each byte (shown from MSB to LSB) is part of a semantic version:
            (major) (minor) (patch) (FIRMWARE_VERSION_TYPE).
            */
            uint flight_sw_version;
            /**
            Middleware version number
            */
            uint middleware_sw_version;
            /**
            Operating system version number
            */
            uint os_sw_version;
            /**
            HW / board version (last 8 bits should be silicon ID, if any). The first 16 bits of this field specify a board
            type from an enumeration stored at https://github.com/PX4/PX4-Bootloader/blob/master/board_types.txt and with
            extensive additions at https://github.com/ArduPilot/ardupilot/blob/master/Tools/AP_Bootloader/board_types.txt
            */
            uint board_version;
            /**
            Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should
            allow to identify the commit using the main version number even for very large code bases.
            */
            [D(8)] byte[] flight_custom_version;
            /**
            Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should
            allow to identify the commit using the main version number even for very large code bases.
            */
            [D(8)] byte[] middleware_custom_version;
            /**
            Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should
            allow to identify the commit using the main version number even for very large code bases.
            */
            [D(8)] byte[] os_custom_version;
            /**
            ID of the board vendor
            */
            ushort vendor_id;
            /**
            ID of the product
            */
            ushort product_id;
            /**
            UID if provided by hardware (see uid2)
            */
            ulong uid;
            /**
            UID if provided by hardware (supersedes the uid field. If this is non-zero, use this field, otherwise use uid)
            */
            [D(18), ExtensionField] byte[] uid2;
        }

        // ═════════════════════════ enums ═════════════════════════

        /**
        Micro air vehicle / autopilot classes. This identifies the individual model.
        */
        enum MAV_AUTOPILOT {
            /**
            Generic autopilot, full support for everything
            */
            MAV_AUTOPILOT_GENERIC = 0,
            /**
            Reserved for future use.
            */
            MAV_AUTOPILOT_RESERVED = 1,
            /**
            SLUGS autopilot, http://slugsuav.soe.ucsc.edu
            */
            MAV_AUTOPILOT_SLUGS = 2,
            /**
            ArduPilot - Plane/Copter/Rover/Sub/Tracker, https://ardupilot.org
            */
            MAV_AUTOPILOT_ARDUPILOTMEGA = 3,
            /**
            OpenPilot, http://openpilot.org
            */
            MAV_AUTOPILOT_OPENPILOT = 4,
            /**
            Generic autopilot only supporting simple waypoints
            */
            MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY = 5,
            /**
            Generic autopilot supporting waypoints and other simple navigation commands
            */
            MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY = 6,
            /**
            Generic autopilot supporting the full mission command set
            */
            MAV_AUTOPILOT_GENERIC_MISSION_FULL = 7,
            /**
            No valid autopilot, e.g. a GCS or other MAVLink component
            */
            MAV_AUTOPILOT_INVALID = 8,
            /**
            PPZ UAV - http://nongnu.org/paparazzi
            */
            MAV_AUTOPILOT_PPZ = 9,
            /**
            UAV Dev Board
            */
            MAV_AUTOPILOT_UDB = 10,
            /**
            FlexiPilot
            */
            MAV_AUTOPILOT_FP = 11,
            /**
            PX4 Autopilot - http://px4.io/
            */
            MAV_AUTOPILOT_PX4 = 12,
            /**
            SMACCMPilot - http://smaccmpilot.org
            */
            MAV_AUTOPILOT_SMACCMPILOT = 13,
            /**
            AutoQuad -- http://autoquad.org
            */
            MAV_AUTOPILOT_AUTOQUAD = 14,
            /**
            Armazila -- http://armazila.com
            */
            MAV_AUTOPILOT_ARMAZILA = 15,
            /**
            Aerob -- http://aerob.ru
            */
            MAV_AUTOPILOT_AEROB = 16,
            /**
            ASLUAV autopilot -- http://www.asl.ethz.ch
            */
            MAV_AUTOPILOT_ASLUAV = 17,
            /**
            SmartAP Autopilot - http://sky-drones.com
            */
            MAV_AUTOPILOT_SMARTAP = 18,
            /**
            AirRails - http://uaventure.com
            */
            MAV_AUTOPILOT_AIRRAILS = 19,
            /**
            Fusion Reflex - https://fusion.engineering
            */
            MAV_AUTOPILOT_REFLEX = 20,
            /**
            Flix quadcopter - https://quadcopter.dev
            */
            MAV_AUTOPILOT_FLIX = 21,
        }

        /**
        MAVLINK component type reported in HEARTBEAT message. Flight controllers must report the type of the vehicle
        on which they are mounted (e.g. MAV_TYPE_OCTOROTOR). All other components must report a value appropriate for
        their type (e.g. a camera must use MAV_TYPE_CAMERA).
        */
        enum MAV_TYPE {
            /**
            Generic micro air vehicle
            */
            MAV_TYPE_GENERIC = 0,
            /**
            Fixed wing aircraft.
            */
            MAV_TYPE_FIXED_WING = 1,
            /**
            Quadrotor
            */
            MAV_TYPE_QUADROTOR = 2,
            /**
            Coaxial helicopter
            */
            MAV_TYPE_COAXIAL = 3,
            /**
            Normal helicopter with tail rotor.
            */
            MAV_TYPE_HELICOPTER = 4,
            /**
            Ground installation
            */
            MAV_TYPE_ANTENNA_TRACKER = 5,
            /**
            Operator control unit / ground control station
            */
            MAV_TYPE_GCS = 6,
            /**
            Airship, controlled
            */
            MAV_TYPE_AIRSHIP = 7,
            /**
            Free balloon, uncontrolled
            */
            MAV_TYPE_FREE_BALLOON = 8,
            /**
            Rocket
            */
            MAV_TYPE_ROCKET = 9,
            /**
            Ground rover
            */
            MAV_TYPE_GROUND_ROVER = 10,
            /**
            Surface vessel, boat, ship
            */
            MAV_TYPE_SURFACE_BOAT = 11,
            /**
            Submarine
            */
            MAV_TYPE_SUBMARINE = 12,
            /**
            Hexarotor
            */
            MAV_TYPE_HEXAROTOR = 13,
            /**
            Octorotor
            */
            MAV_TYPE_OCTOROTOR = 14,
            /**
            Tricopter
            */
            MAV_TYPE_TRICOPTER = 15,
            /**
            Flapping wing
            */
            MAV_TYPE_FLAPPING_WING = 16,
            /**
            Kite
            */
            MAV_TYPE_KITE = 17,
            /**
            Onboard companion controller
            */
            MAV_TYPE_ONBOARD_CONTROLLER = 18,
            /**
            Two-rotor Tailsitter VTOL that additionally uses control surfaces in vertical operation. Note, value
            previously named MAV_TYPE_VTOL_DUOROTOR.
            */
            MAV_TYPE_VTOL_TAILSITTER_DUOROTOR = 19,
            /**
            Quad-rotor Tailsitter VTOL using a V-shaped quad config in vertical operation. Note: value previously named
            MAV_TYPE_VTOL_QUADROTOR.
            */
            MAV_TYPE_VTOL_TAILSITTER_QUADROTOR = 20,
            /**
            Tiltrotor VTOL. Fuselage and wings stay (nominally) horizontal in all flight phases. It able to tilt (some)
            rotors to provide thrust in cruise flight.
            */
            MAV_TYPE_VTOL_TILTROTOR = 21,
            /**
            VTOL with separate fixed rotors for hover and cruise flight. Fuselage and wings stay (nominally) horizontal in
            all flight phases.
            */
            MAV_TYPE_VTOL_FIXEDROTOR = 22,
            /**
            Tailsitter VTOL. Fuselage and wings orientation changes depending on flight phase: vertical for hover,
            horizontal for cruise. Use more specific VTOL MAV_TYPE_VTOL_TAILSITTER_DUOROTOR or
            MAV_TYPE_VTOL_TAILSITTER_QUADROTOR if appropriate.
            */
            MAV_TYPE_VTOL_TAILSITTER = 23,
            /**
            Tiltwing VTOL. Fuselage stays horizontal in all flight phases. The whole wing, along with any attached engine,
            can tilt between vertical and horizontal mode.
            */
            MAV_TYPE_VTOL_TILTWING = 24,
            /**
            VTOL reserved 5
            */
            MAV_TYPE_VTOL_RESERVED5 = 25,
            /**
            Gimbal
            */
            MAV_TYPE_GIMBAL = 26,
            /**
            ADSB system
            */
            MAV_TYPE_ADSB = 27,
            /**
            Steerable, nonrigid airfoil
            */
            MAV_TYPE_PARAFOIL = 28,
            /**
            Dodecarotor
            */
            MAV_TYPE_DODECAROTOR = 29,
            /**
            Camera
            */
            MAV_TYPE_CAMERA = 30,
            /**
            Charging station
            */
            MAV_TYPE_CHARGING_STATION = 31,
            /**
            FLARM collision avoidance system
            */
            MAV_TYPE_FLARM = 32,
            /**
            Servo
            */
            MAV_TYPE_SERVO = 33,
            /**
            Open Drone ID. See https://mavlink.io/en/services/opendroneid.html.
            */
            MAV_TYPE_ODID = 34,
            /**
            Decarotor
            */
            MAV_TYPE_DECAROTOR = 35,
            /**
            Battery
            */
            MAV_TYPE_BATTERY = 36,
            /**
            Parachute
            */
            MAV_TYPE_PARACHUTE = 37,
            /**
            Log
            */
            MAV_TYPE_LOG = 38,
            /**
            OSD
            */
            MAV_TYPE_OSD = 39,
            /**
            IMU
            */
            MAV_TYPE_IMU = 40,
            /**
            GPS
            */
            MAV_TYPE_GPS = 41,
            /**
            Winch
            */
            MAV_TYPE_WINCH = 42,
            /**
            Generic multirotor that does not fit into a specific type or whose type is unknown
            */
            MAV_TYPE_GENERIC_MULTIROTOR = 43,
            /**
            Illuminator. An illuminator is a light source that is used for lighting up dark areas external to the system:
            e.g. a torch or searchlight (as opposed to a light source for illuminating the system itself, e.g. an
            indicator light).
            */
            MAV_TYPE_ILLUMINATOR = 44,
            /**
            Orbiter spacecraft. Includes satellites orbiting terrestrial and extra-terrestrial bodies. Follows NASA
            Spacecraft Classification.
            */
            MAV_TYPE_SPACECRAFT_ORBITER = 45,
            /**
            A generic four-legged ground vehicle (e.g., a robot dog).
            */
            MAV_TYPE_GROUND_QUADRUPED = 46,
            /**
            VTOL hybrid of helicopter and autogyro. It has a main rotor for lift and separate propellers for forward
            flight. The rotor must be powered for hover but can autorotate in cruise flight. See:
            https://en.wikipedia.org/wiki/Gyrodyne
            */
            MAV_TYPE_VTOL_GYRODYNE = 47,
            /**
            Gripper
            */
            MAV_TYPE_GRIPPER = 48,
            /**
            Radio
            */
            MAV_TYPE_RADIO = 49,
        }

        /**
        These flags encode the MAV mode, see MAV_MODE enum for useful combinations.
        */
        [Flags]
        enum MAV_MODE_FLAG {
            /**
            0b10000000 MAV safety set to armed. Motors are enabled / running / can start. Ready to fly. Additional note:
            this flag is to be ignored when sent in the command MAV_CMD_DO_SET_MODE and MAV_CMD_COMPONENT_ARM_DISARM shall
            be used instead. The flag can still be used to report the armed state.
            */
            MAV_MODE_FLAG_SAFETY_ARMED = 128,
            /**
            0b01000000 remote control input is enabled.
            */
            MAV_MODE_FLAG_MANUAL_INPUT_ENABLED = 64,
            /**
            0b00100000 hardware in the loop simulation. All motors / actuators are blocked, but internal software is full
            operational.
            */
            MAV_MODE_FLAG_HIL_ENABLED = 32,
            /**
            0b00010000 system stabilizes electronically its attitude (and optionally position). It needs however further
            control inputs to move around.
            */
            MAV_MODE_FLAG_STABILIZE_ENABLED = 16,
            /**
            0b00001000 guided mode enabled, system flies waypoints / mission items.
            */
            MAV_MODE_FLAG_GUIDED_ENABLED = 8,
            /**
            0b00000100 autonomous mode enabled, system finds its own goal positions. Guided flag can be set or not,
            depends on the actual implementation.
            */
            MAV_MODE_FLAG_AUTO_ENABLED = 4,
            /**
            0b00000010 system has a test mode enabled. This flag is intended for temporary system tests and should not be
            used for stable implementations.
            */
            MAV_MODE_FLAG_TEST_ENABLED = 2,
            /**
            0b00000001 system-specific custom mode is enabled. When using this flag to enable a custom mode all other
            flags should be ignored.
            */
            MAV_MODE_FLAG_CUSTOM_MODE_ENABLED = 1,
        }

        /**
        These values encode the bit positions of the decode position. These values can be used to read the value of a
        flag bit by combining the base_mode variable with AND with the flag position value. The result will be either
        0 or 1, depending on if the flag is set or not.
        */
        [Flags]
        enum MAV_MODE_FLAG_DECODE_POSITION {
            /**
            First bit:  10000000
            */
            MAV_MODE_FLAG_DECODE_POSITION_SAFETY = 128,
            /**
            Second bit: 01000000
            */
            MAV_MODE_FLAG_DECODE_POSITION_MANUAL = 64,
            /**
            Third bit:  00100000
            */
            MAV_MODE_FLAG_DECODE_POSITION_HIL = 32,
            /**
            Fourth bit: 00010000
            */
            MAV_MODE_FLAG_DECODE_POSITION_STABILIZE = 16,
            /**
            Fifth bit:  00001000
            */
            MAV_MODE_FLAG_DECODE_POSITION_GUIDED = 8,
            /**
            Sixth bit:   00000100
            */
            MAV_MODE_FLAG_DECODE_POSITION_AUTO = 4,
            /**
            Seventh bit: 00000010
            */
            MAV_MODE_FLAG_DECODE_POSITION_TEST = 2,
            /**
            Eighth bit: 00000001
            */
            MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE = 1,
        }

        enum MAV_STATE {
            /**
            Uninitialized system, state is unknown.
            */
            MAV_STATE_UNINIT = 0,
            /**
            System is booting up.
            */
            MAV_STATE_BOOT = 1,
            /**
            System is calibrating and not flight-ready.
            */
            MAV_STATE_CALIBRATING = 2,
            /**
            System is grounded and on standby. It can be launched any time.
            */
            MAV_STATE_STANDBY = 3,
            /**
            System is active and might be already airborne. Motors are engaged.
            */
            MAV_STATE_ACTIVE = 4,
            /**
            System is in a non-normal flight mode (failsafe). It can however still navigate.
            */
            MAV_STATE_CRITICAL = 5,
            /**
            System is in a non-normal flight mode (failsafe). It lost control over parts or over the whole airframe. It is
            in mayday and going down.
            */
            MAV_STATE_EMERGENCY = 6,
            /**
            System just initialized its power-down sequence, will shut down now.
            */
            MAV_STATE_POWEROFF = 7,
            /**
            System is terminating itself (failsafe or commanded).
            */
            MAV_STATE_FLIGHT_TERMINATION = 8,
        }

        /**
        Legacy component ID values for particular types of hardware/software that might make up a MAVLink system
        (autopilot, cameras, servos, avoidance systems etc.).
        Components are not required or expected to use IDs with names that correspond to their type or function, but
        may choose to do so.
        Using an ID that matches the type may slightly reduce the chances of component id clashes, as, for historical
        reasons, it is less likely to be used by some other type of component.
        System integration will still need to ensure that all components have unique IDs.
        Component IDs are used for addressing messages to a particular component within a system.
        A component can use any unique ID between 1 and 255 (MAV_COMP_ID_ALL value is the broadcast address, used to
        send to all components).
        Historically component ID were also used for identifying the type of component.
        New code must not use component IDs to infer the component type, but instead check the MAV_TYPE in the
        HEARTBEAT message!
        */
        enum MAV_COMPONENT {
            /**
            Target id (target_component) used to broadcast messages to all components of the receiving system. Components
            should attempt to process messages with this component ID and forward to components on any other interfaces.
            Note: This is not a valid *source* component id for a message.
            */
            MAV_COMP_ID_ALL = 0,
            /**
            System flight controller component ("autopilot"). Only one autopilot is expected in a particular system.
            */
            MAV_COMP_ID_AUTOPILOT1 = 1,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER1 = 25,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER2 = 26,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER3 = 27,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER4 = 28,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER5 = 29,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER6 = 30,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER7 = 31,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER8 = 32,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER9 = 33,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER10 = 34,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER11 = 35,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER12 = 36,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER13 = 37,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER14 = 38,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER15 = 39,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER16 = 40,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER17 = 41,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER18 = 42,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER19 = 43,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER20 = 44,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER21 = 45,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER22 = 46,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER23 = 47,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER24 = 48,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER25 = 49,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER26 = 50,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER27 = 51,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER28 = 52,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER29 = 53,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER30 = 54,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER31 = 55,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER32 = 56,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER33 = 57,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER34 = 58,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER35 = 59,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER36 = 60,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER37 = 61,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER38 = 62,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER39 = 63,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER40 = 64,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER41 = 65,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER42 = 66,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER43 = 67,
            /**
            Telemetry radio (e.g. SiK radio, or other component that emits RADIO_STATUS messages).
            */
            MAV_COMP_ID_TELEMETRY_RADIO = 68,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER45 = 69,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER46 = 70,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER47 = 71,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER48 = 72,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER49 = 73,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER50 = 74,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER51 = 75,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER52 = 76,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER53 = 77,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER54 = 78,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER55 = 79,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER56 = 80,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER57 = 81,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER58 = 82,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER59 = 83,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER60 = 84,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER61 = 85,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER62 = 86,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER63 = 87,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER64 = 88,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER65 = 89,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER66 = 90,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER67 = 91,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER68 = 92,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER69 = 93,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER70 = 94,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER71 = 95,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER72 = 96,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER73 = 97,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER74 = 98,
            /**
            Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published
            by components outside of the private network.
            */
            MAV_COMP_ID_USER75 = 99,
            /**
            Camera #1.
            */
            MAV_COMP_ID_CAMERA = 100,
            /**
            Camera #2.
            */
            MAV_COMP_ID_CAMERA2 = 101,
            /**
            Camera #3.
            */
            MAV_COMP_ID_CAMERA3 = 102,
            /**
            Camera #4.
            */
            MAV_COMP_ID_CAMERA4 = 103,
            /**
            Camera #5.
            */
            MAV_COMP_ID_CAMERA5 = 104,
            /**
            Camera #6.
            */
            MAV_COMP_ID_CAMERA6 = 105,
            /**
            Radio #1.
            */
            MAV_COMP_ID_RADIO = 110,
            /**
            Radio #2.
            */
            MAV_COMP_ID_RADIO2 = 111,
            /**
            Radio #3.
            */
            MAV_COMP_ID_RADIO3 = 112,
            /**
            Servo #1.
            */
            MAV_COMP_ID_SERVO1 = 140,
            /**
            Servo #2.
            */
            MAV_COMP_ID_SERVO2 = 141,
            /**
            Servo #3.
            */
            MAV_COMP_ID_SERVO3 = 142,
            /**
            Servo #4.
            */
            MAV_COMP_ID_SERVO4 = 143,
            /**
            Servo #5.
            */
            MAV_COMP_ID_SERVO5 = 144,
            /**
            Servo #6.
            */
            MAV_COMP_ID_SERVO6 = 145,
            /**
            Servo #7.
            */
            MAV_COMP_ID_SERVO7 = 146,
            /**
            Servo #8.
            */
            MAV_COMP_ID_SERVO8 = 147,
            /**
            Servo #9.
            */
            MAV_COMP_ID_SERVO9 = 148,
            /**
            Servo #10.
            */
            MAV_COMP_ID_SERVO10 = 149,
            /**
            Servo #11.
            */
            MAV_COMP_ID_SERVO11 = 150,
            /**
            Servo #12.
            */
            MAV_COMP_ID_SERVO12 = 151,
            /**
            Servo #13.
            */
            MAV_COMP_ID_SERVO13 = 152,
            /**
            Servo #14.
            */
            MAV_COMP_ID_SERVO14 = 153,
            /**
            Gimbal #1.
            */
            MAV_COMP_ID_GIMBAL = 154,
            /**
            Logging component.
            */
            MAV_COMP_ID_LOG = 155,
            /**
            Automatic Dependent Surveillance-Broadcast (ADS-B) component.
            */
            MAV_COMP_ID_ADSB = 156,
            /**
            On Screen Display (OSD) devices for video links.
            */
            MAV_COMP_ID_OSD = 157,
            /**
            Generic autopilot peripheral component ID. Meant for devices that do not implement the parameter microservice.
            */
            MAV_COMP_ID_PERIPHERAL = 158,
            /**
            Gimbal ID for QX1.
            ⚠ DEPRECATED since 2018-11, replaced by MAV_COMP_ID_GIMBAL: All gimbals should use MAV_COMP_ID_GIMBAL.
            */
            MAV_COMP_ID_QX1_GIMBAL = 159,
            /**
            FLARM collision alert component.
            */
            MAV_COMP_ID_FLARM = 160,
            /**
            Parachute component.
            */
            MAV_COMP_ID_PARACHUTE = 161,
            /**
            Winch component.
            */
            MAV_COMP_ID_WINCH = 169,
            /**
            Gimbal #2.
            */
            MAV_COMP_ID_GIMBAL2 = 171,
            /**
            Gimbal #3.
            */
            MAV_COMP_ID_GIMBAL3 = 172,
            /**
            Gimbal #4
            */
            MAV_COMP_ID_GIMBAL4 = 173,
            /**
            Gimbal #5.
            */
            MAV_COMP_ID_GIMBAL5 = 174,
            /**
            Gimbal #6.
            */
            MAV_COMP_ID_GIMBAL6 = 175,
            /**
            Battery #1.
            */
            MAV_COMP_ID_BATTERY = 180,
            /**
            Battery #2.
            */
            MAV_COMP_ID_BATTERY2 = 181,
            /**
            CAN over MAVLink client.
            */
            MAV_COMP_ID_MAVCAN = 189,
            /**
            Component that can generate/supply a mission flight plan (e.g. GCS or developer API).
            */
            MAV_COMP_ID_MISSIONPLANNER = 190,
            /**
            Component that lives on the onboard computer (companion computer) and has some generic functionalities, such
            as settings system parameters and monitoring the status of some processes that don't directly speak mavlink
            and so on.
            */
            MAV_COMP_ID_ONBOARD_COMPUTER = 191,
            /**
            Component that lives on the onboard computer (companion computer) and has some generic functionalities, such
            as settings system parameters and monitoring the status of some processes that don't directly speak mavlink
            and so on.
            */
            MAV_COMP_ID_ONBOARD_COMPUTER2 = 192,
            /**
            Component that lives on the onboard computer (companion computer) and has some generic functionalities, such
            as settings system parameters and monitoring the status of some processes that don't directly speak mavlink
            and so on.
            */
            MAV_COMP_ID_ONBOARD_COMPUTER3 = 193,
            /**
            Component that lives on the onboard computer (companion computer) and has some generic functionalities, such
            as settings system parameters and monitoring the status of some processes that don't directly speak mavlink
            and so on.
            */
            MAV_COMP_ID_ONBOARD_COMPUTER4 = 194,
            /**
            Component that finds an optimal path between points based on a certain constraint (e.g. minimum snap, shortest
            path, cost, etc.).
            */
            MAV_COMP_ID_PATHPLANNER = 195,
            /**
            Component that plans a collision free path between two points.
            */
            MAV_COMP_ID_OBSTACLE_AVOIDANCE = 196,
            /**
            Component that provides position estimates using VIO techniques.
            */
            MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY = 197,
            /**
            Component that manages pairing of vehicle and GCS.
            */
            MAV_COMP_ID_PAIRING_MANAGER = 198,
            /**
            Inertial Measurement Unit (IMU) #1.
            */
            MAV_COMP_ID_IMU = 200,
            /**
            Inertial Measurement Unit (IMU) #2.
            */
            MAV_COMP_ID_IMU_2 = 201,
            /**
            Inertial Measurement Unit (IMU) #3.
            */
            MAV_COMP_ID_IMU_3 = 202,
            /**
            GPS #1.
            */
            MAV_COMP_ID_GPS = 220,
            /**
            GPS #2.
            */
            MAV_COMP_ID_GPS2 = 221,
            /**
            Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
            */
            MAV_COMP_ID_ODID_TXRX_1 = 236,
            /**
            Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
            */
            MAV_COMP_ID_ODID_TXRX_2 = 237,
            /**
            Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
            */
            MAV_COMP_ID_ODID_TXRX_3 = 238,
            /**
            Component to bridge MAVLink to UDP (i.e. from a UART).
            */
            MAV_COMP_ID_UDP_BRIDGE = 240,
            /**
            Component to bridge to UART (i.e. from UDP).
            */
            MAV_COMP_ID_UART_BRIDGE = 241,
            /**
            Component handling TUNNEL messages (e.g. vendor specific GUI of a component).
            */
            MAV_COMP_ID_TUNNEL_NODE = 242,
            /**
            Illuminator
            */
            MAV_COMP_ID_ILLUMINATOR = 243,
            /**
            Deprecated, don't use. Component for handling system messages (e.g. to ARM, takeoff, etc.).
            ⚠ DEPRECATED since 2018-11, replaced by MAV_COMP_ID_ALL: System control does not require a separate component
            ID. Instead, system commands should be sent with target_component=MAV_COMP_ID_ALL allowing the target
            component to use any appropriate component id.
            */
            MAV_COMP_ID_SYSTEM_CONTROL = 250,
        }

        /**
        Enum used to indicate true or false (also: success or failure, enabled or disabled, active or inactive).
        */
        enum MAV_BOOL {
            /**
            False.
            */
            MAV_BOOL_FALSE = 0,
            /**
            True.
            */
            MAV_BOOL_TRUE = 1,
        }

        /**
        Bitmask of (optional) autopilot capabilities (64 bit). If a bit is set, the autopilot supports this
        capability.
        */
        [Flags]
        enum MAV_PROTOCOL_CAPABILITY {
            /**
            Autopilot supports the MISSION_ITEM float message type.
            Note that MISSION_ITEM is deprecated, and autopilots should use MISSION_ITEM_INT instead.
            */
            MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT = 1,
            /**
            Autopilot supports the new param float message type.
            ⚠ DEPRECATED since 2022-03, replaced by MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST
            */
            MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT = 2,
            /**
            Autopilot supports MISSION_ITEM_INT scaled integer message type.
            Note that this flag must always be set if missions are supported, because missions must always use
            MISSION_ITEM_INT (rather than MISSION_ITEM, which is deprecated).
            */
            MAV_PROTOCOL_CAPABILITY_MISSION_INT = 4,
            /**
            Autopilot supports COMMAND_INT scaled integer message type.
            */
            MAV_PROTOCOL_CAPABILITY_COMMAND_INT = 8,
            /**
            Parameter protocol uses byte-wise encoding of parameter values into param_value (float) fields:
            https://mavlink.io/en/services/parameter.html#parameter-encoding.
            Note that either this flag or MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST should be set if the parameter
            protocol is supported.
            */
            MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE = 16,
            /**
            Autopilot supports the File Transfer Protocol v1: https://mavlink.io/en/services/ftp.html.
            */
            MAV_PROTOCOL_CAPABILITY_FTP = 32,
            /**
            Autopilot supports the SET_ATTITUDE_TARGET message (for commanding attitude from an offboard controller).
            */
            MAV_PROTOCOL_CAPABILITY_SET_ATTITUDE_TARGET = 64,
            /**
            Autopilot supports the SET_POSITION_TARGET_LOCAL_NED message (for commanding position and velocity targets in
            local NED frame).
            */
            MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_LOCAL_NED = 128,
            /**
            Autopilot supports the SET_POSITION_TARGET_GLOBAL_INT message (for commanding position and velocity targets in
            global scaled integers).
            */
            MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_GLOBAL_INT = 256,
            /**
            Autopilot supports terrain protocol / data handling.
            */
            MAV_PROTOCOL_CAPABILITY_TERRAIN = 512,
            /**
            Reserved for future use.
            */
            MAV_PROTOCOL_CAPABILITY_RESERVED3 = 1024,
            /**
            Autopilot supports the MAV_CMD_DO_FLIGHTTERMINATION command (flight termination).
            */
            MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION = 2048,
            /**
            Autopilot supports onboard compass calibration.
            */
            MAV_PROTOCOL_CAPABILITY_COMPASS_CALIBRATION = 4096,
            /**
            Autopilot supports MAVLink version 2.
            */
            MAV_PROTOCOL_CAPABILITY_MAVLINK2 = 8192,
            /**
            Autopilot supports mission fence protocol.
            */
            MAV_PROTOCOL_CAPABILITY_MISSION_FENCE = 16384,
            /**
            Autopilot supports mission rally point protocol.
            */
            MAV_PROTOCOL_CAPABILITY_MISSION_RALLY = 32768,
            /**
            Reserved for future use.
            */
            MAV_PROTOCOL_CAPABILITY_RESERVED2 = 65536,
            /**
            Parameter protocol uses C-cast of parameter values to set the param_value (float) fields:
            https://mavlink.io/en/services/parameter.html#parameter-encoding.
            Note that either this flag or MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE should be set if the parameter
            protocol is supported.
            */
            MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST = 131072,
            /**
            This component implements/is a gimbal manager. This means the GIMBAL_MANAGER_INFORMATION, and other messages
            can be requested.
            */
            MAV_PROTOCOL_CAPABILITY_COMPONENT_IMPLEMENTS_GIMBAL_MANAGER = 262144,
            /**
            Component supports locking control to a particular GCS independent of its system (via
            MAV_CMD_REQUEST_OPERATOR_CONTROL).
            🚧 WIP
            */
            MAV_PROTOCOL_CAPABILITY_COMPONENT_ACCEPTS_GCS_CONTROL = 524288,
            /**
            Autopilot has a connected gripper. MAVLink Grippers would set MAV_TYPE_GRIPPER instead.
            🚧 WIP
            */
            MAV_PROTOCOL_CAPABILITY_GRIPPER = 1048576,
        }

        /**
        These values define the type of firmware release.  These values indicate the first version or release of this
        type.  For example the first alpha release would be 64, the second would be 65.
        */
        enum FIRMWARE_VERSION_TYPE {
            /**
            development release
            */
            FIRMWARE_VERSION_TYPE_DEV = 0,
            /**
            alpha release
            */
            FIRMWARE_VERSION_TYPE_ALPHA = 64,
            /**
            beta release
            */
            FIRMWARE_VERSION_TYPE_BETA = 128,
            /**
            release candidate
            */
            FIRMWARE_VERSION_TYPE_RC = 192,
            /**
            official stable release
            */
            FIRMWARE_VERSION_TYPE_OFFICIAL = 255,
        }

        // ═════════════════════════ SI units (mirrored from mavschema.xsd) ═════════════════════════

        /** Non-transmittable constants container with every unit string MAVLink allows; [Units] attributes reference it. */
        public struct SI_Unit {
            public struct time {
                public const string s            = "s"; // seconds
                public const string ds           = "ds"; // deciseconds
                public const string cs           = "cs"; // centiseconds
                public const string ms           = "ms"; // milliseconds
                public const string us           = "us"; // microseconds
                public const string ns           = "ns"; // nanoseconds
                public const string Hz           = "Hz"; // Herz
                public const string MHz          = "MHz"; // Mega-Herz
            }

            public struct distance {
                public const string km           = "km"; // kilometres
                public const string dam          = "dam"; // decametres
                public const string m            = "m"; // metres
                public const string m_2          = "m^2"; // metres squared (typically used in variance)
                public const string m_s          = "m/s"; // metres per second
                public const string m_s_s        = "m/s/s"; // metres per second per second
                public const string m_s_5        = "m/s*5"; // metres per second * 5 required from dagar for HIGH_LATENCY2 message
                public const string dm           = "dm"; // decimetres
                public const string dm_s         = "dm/s"; // decimetres per second
                public const string cm           = "cm"; // centimetres
                public const string cm_2         = "cm^2"; // centimetres squared (typically used in variance)
                public const string cm_s         = "cm/s"; // centimetres per second
                public const string mm           = "mm"; // millimetres
                public const string mm_s         = "mm/s"; // millimetres per second
                public const string mm_h         = "mm/h"; // millimetres per hour
            }

            public struct temperature {
                public const string K            = "K"; // Kelvin
                public const string degC         = "degC"; // degrees Celsius
                public const string cdegC        = "cdegC"; // centi degrees Celsius
            }

            public struct angle {
                public const string rad          = "rad"; // radians
                public const string rad_s        = "rad/s"; // radians per second
                public const string mrad_s       = "mrad/s"; // milli-radians per second
                public const string deg          = "deg"; // degrees
                public const string deg_2        = "deg/2"; // degrees/2 required from dagar for HIGH_LATENCY2 message
                public const string ddeg_s       = "ddeg/s"; // decidegrees per second (AIS_VESSEL only, not recommended elsewhere)
                public const string deg_s        = "deg/s"; // degrees per second
                public const string cdeg         = "cdeg"; // centidegrees
                public const string cdeg_s       = "cdeg/s"; // centidegrees per second
                public const string degE5        = "degE5"; // degrees * 1E5
                public const string degE7        = "degE7"; // degrees * 1E7
                public const string rpm          = "rpm"; // rotations per minute
            }

            public struct electricity {
                public const string V            = "V"; // Volt
                public const string cV           = "cV"; // centi-Volt
                public const string mV           = "mV"; // milli-Volt
                public const string A            = "A"; // Ampere
                public const string cA           = "cA"; // centi-Ampere
                public const string mA           = "mA"; // milli-Ampere
                public const string mAh          = "mAh"; // milli-Ampere hour
                public const string Ah           = "Ah"; // Ampere hour
            }

            public struct magnetism {
                public const string mT           = "mT"; // milli-Tesla
                public const string gauss        = "gauss"; // Gauss
                public const string mgauss       = "mgauss"; // milli-Gauss
            }

            public struct energy {
                public const string hJ           = "hJ"; // hecto-Joule
            }

            public struct power {
                public const string W            = "W"; // Watt
            }

            public struct force {
                public const string mG           = "mG"; // milli-G
            }

            public struct mass {
                public const string g            = "g"; // grams
                public const string kg           = "kg"; // kilograms
            }

            public struct pressure {
                public const string Pa           = "Pa"; // Pascal
                public const string hPa          = "hPa"; // hecto-Pascal
                public const string kPa          = "kPa"; // kilo-Pascal
                public const string mbar         = "mbar"; // millibar
            }

            public struct ratio {
                public const string percent      = "%"; // percent
                public const string decipercent  = "d%"; // decipercent
                public const string centipercent = "c%"; // centipercent
                public const string dB           = "dB"; // Deci-Bell
                public const string dBm          = "dBm"; // Deci-Bell-milliwatts
            }

            public struct digital {
                public const string KiB          = "KiB"; // Kibibyte (1024 bytes)
                public const string KiB_s        = "KiB/s"; // Kibibyte (1024 bytes) per second
                public const string MiB          = "MiB"; // Mebibyte (1024*1024 bytes)
                public const string MiB_s        = "MiB/s"; // Mebibyte (1024*1024 bytes) per second
                public const string bytes        = "bytes"; // bytes
                public const string bytes_s      = "bytes/s"; // bytes per second
                public const string bits_s       = "bits/s"; // bits per second
                public const string pix          = "pix"; // pixels
                public const string dpix         = "dpix"; // decipixels
            }

            public struct flow {
                public const string g_min        = "g/min"; // grams/minute
                public const string cm_3_min     = "cm^3/min"; // cubic centimetres/minute
                public const string L_h          = "L/h"; // Litres/hour
            }

            public struct volume {
                public const string cm_3         = "cm^3"; // cubic centimetres
                public const string l            = "l"; // litres
                public const string L            = "L"; // Litres
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // MAVLink defines no network topology (packets only carry system_id / component_id), so the demo
        // invents two hosts and lets either side send any message without changing state.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct GroundControl : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct MicroAirVehicle : Host { }

        interface CommunicationChannel : Connects<GroundControl, MicroAirVehicle> {
            // Every message class of the dialect, in both directions; the FSM never transitions.
            // The recursive @scope would also collect the metadata attribute classes declared at the end of
            // this interface, so they are filtered out by name.
            // Replace with explicit l____________ / ____________r branches to route messages per host.
            [_____lr_____<@standard>(SkipName: @"Attribute$")]
            struct Start { }
        }

        // ═════════════════════════ MAVLink metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants
        // attached to the field, so units, invalid markers, display hints etc. stay available at runtime.
        // They must live inside the project interface (the agent expects every class in a project); the
        // connection's branch excludes them from its pack scope with SkipName.

        /** SI unit of a numeric field (a SI_Unit constant). */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** Value (or, for arrays, the [value] / [value:] / [v1,,v3,] notation) that marks the field as not set. */
        public class InvalidAttribute : Attribute { public InvalidAttribute(string value) { } }

        /** The field identifies the sensor / battery instance the message is about. */
        public class InstanceAttribute : Attribute { }

        /** UI hint, e.g. "bitmask": show the enum values as check boxes. */
        public class DisplayAttribute : Attribute { public DisplayAttribute(string hint) { } }

        /** printf-style display format. */
        public class PrintFormatAttribute : Attribute { public PrintFormatAttribute(string format) { } }

        /** Default value of the field. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** Scale factor: actual value = stated value * multiplier. */
        public class MultiplierAttribute : Attribute { public MultiplierAttribute(string factor) { } }

        /** Minimum value hint for UIs (not a wire constraint: [Invalid] markers may lie outside it). */
        public class MinValueAttribute : Attribute { public MinValueAttribute(double value) { } public MinValueAttribute(string value) { } }

        /** Maximum value hint for UIs (not a wire constraint: [Invalid] markers may lie outside it). */
        public class MaxValueAttribute : Attribute { public MaxValueAttribute(double value) { } public MaxValueAttribute(string value) { } }

        /** Declared after the &lt;extensions/&gt; marker: present in MAVLink 2 frames only. */
        public class ExtensionFieldAttribute : Attribute { }
    }
}
