// Generated by MavLink2AdHoc (https://github.com/AdHoc-Protocol) from test.xml
// Sources, in emission order: test.xml
// MAVLink protocol version: 3
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.mavlink {
    /**
        <see cref = 'TEST_TYPES'/>
    */
    public interface test {

        // ═════════════════════════ messages of test.xml ═════════════════════════

        /**
        Test all field types
        */
        class TEST_TYPES {
            public const int mavlink_message_id = 17000;
            /**
            char
            */
            char c;
            /**
            string
            */
            [D(+10)] string s;
            /**
            uint8_t
            */
            byte u8;
            /**
            uint16_t
            */
            ushort u16;
            /**
            uint32_t
            */
            [PrintFormat("0x%08x")] uint u32;
            /**
            uint64_t
            */
            ulong u64;
            /**
            int8_t
            */
            sbyte s8;
            /**
            int16_t
            */
            short s16;
            /**
            int32_t
            */
            int s32;
            /**
            int64_t
            */
            long s64;
            /**
            float
            */
            float f;
            /**
            double
            */
            double d;
            /**
            uint8_t_array
            */
            [D(3)] byte[] u8_array;
            /**
            uint16_t_array
            */
            [D(3)] ushort[] u16_array;
            /**
            uint32_t_array
            */
            [D(3)] uint[] u32_array;
            /**
            uint64_t_array
            */
            [D(3)] ulong[] u64_array;
            /**
            int8_t_array
            */
            [D(3)] sbyte[] s8_array;
            /**
            int16_t_array
            */
            [D(3)] short[] s16_array;
            /**
            int32_t_array
            */
            [D(3)] int[] s32_array;
            /**
            int64_t_array
            */
            [D(3)] long[] s64_array;
            /**
            float_array
            */
            [D(3)] float[] f_array;
            /**
            double_array
            */
            [D(3)] double[] d_array;
        }

        // ═════════════════════════ enums ═════════════════════════

        // ═════════════════════════ SI units (mirrored from mavschema.xsd) ═════════════════════════

        /** Non-transmittable constants container with every unit string MAVLink allows; [Units] attributes reference it. */
        public struct SI_Unit {
            public struct time {
                public const string s            = "s"; // seconds
                public const string ds           = "ds"; // deciseconds
                public const string cs           = "cs"; // centiseconds
                public const string ms           = "ms"; // milliseconds
                public const string us           = "us"; // microseconds
                public const string ns           = "ns"; // nanoseconds
                public const string Hz           = "Hz"; // Herz
                public const string MHz          = "MHz"; // Mega-Herz
            }

            public struct distance {
                public const string km           = "km"; // kilometres
                public const string dam          = "dam"; // decametres
                public const string m            = "m"; // metres
                public const string m_2          = "m^2"; // metres squared (typically used in variance)
                public const string m_s          = "m/s"; // metres per second
                public const string m_s_s        = "m/s/s"; // metres per second per second
                public const string m_s_5        = "m/s*5"; // metres per second * 5 required from dagar for HIGH_LATENCY2 message
                public const string dm           = "dm"; // decimetres
                public const string dm_s         = "dm/s"; // decimetres per second
                public const string cm           = "cm"; // centimetres
                public const string cm_2         = "cm^2"; // centimetres squared (typically used in variance)
                public const string cm_s         = "cm/s"; // centimetres per second
                public const string mm           = "mm"; // millimetres
                public const string mm_s         = "mm/s"; // millimetres per second
                public const string mm_h         = "mm/h"; // millimetres per hour
            }

            public struct temperature {
                public const string K            = "K"; // Kelvin
                public const string degC         = "degC"; // degrees Celsius
                public const string cdegC        = "cdegC"; // centi degrees Celsius
            }

            public struct angle {
                public const string rad          = "rad"; // radians
                public const string rad_s        = "rad/s"; // radians per second
                public const string mrad_s       = "mrad/s"; // milli-radians per second
                public const string deg          = "deg"; // degrees
                public const string deg_2        = "deg/2"; // degrees/2 required from dagar for HIGH_LATENCY2 message
                public const string ddeg_s       = "ddeg/s"; // decidegrees per second (AIS_VESSEL only, not recommended elsewhere)
                public const string deg_s        = "deg/s"; // degrees per second
                public const string cdeg         = "cdeg"; // centidegrees
                public const string cdeg_s       = "cdeg/s"; // centidegrees per second
                public const string degE5        = "degE5"; // degrees * 1E5
                public const string degE7        = "degE7"; // degrees * 1E7
                public const string rpm          = "rpm"; // rotations per minute
            }

            public struct electricity {
                public const string V            = "V"; // Volt
                public const string cV           = "cV"; // centi-Volt
                public const string mV           = "mV"; // milli-Volt
                public const string A            = "A"; // Ampere
                public const string cA           = "cA"; // centi-Ampere
                public const string mA           = "mA"; // milli-Ampere
                public const string mAh          = "mAh"; // milli-Ampere hour
                public const string Ah           = "Ah"; // Ampere hour
            }

            public struct magnetism {
                public const string mT           = "mT"; // milli-Tesla
                public const string gauss        = "gauss"; // Gauss
                public const string mgauss       = "mgauss"; // milli-Gauss
            }

            public struct energy {
                public const string hJ           = "hJ"; // hecto-Joule
            }

            public struct power {
                public const string W            = "W"; // Watt
            }

            public struct force {
                public const string mG           = "mG"; // milli-G
            }

            public struct mass {
                public const string g            = "g"; // grams
                public const string kg           = "kg"; // kilograms
            }

            public struct pressure {
                public const string Pa           = "Pa"; // Pascal
                public const string hPa          = "hPa"; // hecto-Pascal
                public const string kPa          = "kPa"; // kilo-Pascal
                public const string mbar         = "mbar"; // millibar
            }

            public struct ratio {
                public const string percent      = "%"; // percent
                public const string decipercent  = "d%"; // decipercent
                public const string centipercent = "c%"; // centipercent
                public const string dB           = "dB"; // Deci-Bell
                public const string dBm          = "dBm"; // Deci-Bell-milliwatts
            }

            public struct digital {
                public const string KiB          = "KiB"; // Kibibyte (1024 bytes)
                public const string KiB_s        = "KiB/s"; // Kibibyte (1024 bytes) per second
                public const string MiB          = "MiB"; // Mebibyte (1024*1024 bytes)
                public const string MiB_s        = "MiB/s"; // Mebibyte (1024*1024 bytes) per second
                public const string bytes        = "bytes"; // bytes
                public const string bytes_s      = "bytes/s"; // bytes per second
                public const string bits_s       = "bits/s"; // bits per second
                public const string pix          = "pix"; // pixels
                public const string dpix         = "dpix"; // decipixels
            }

            public struct flow {
                public const string g_min        = "g/min"; // grams/minute
                public const string cm_3_min     = "cm^3/min"; // cubic centimetres/minute
                public const string L_h          = "L/h"; // Litres/hour
            }

            public struct volume {
                public const string cm_3         = "cm^3"; // cubic centimetres
                public const string l            = "l"; // litres
                public const string L            = "L"; // Litres
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // MAVLink defines no network topology (packets only carry system_id / component_id), so the demo
        // invents two hosts and lets either side send any message without changing state.

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct GroundControl : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct MicroAirVehicle : Host { }

        interface CommunicationChannel : Connects<GroundControl, MicroAirVehicle> {
            // Every message class of the dialect, in both directions; the FSM never transitions.
            // The recursive @scope would also collect the metadata attribute classes declared at the end of
            // this interface, so they are filtered out by name.
            // Replace with explicit l____________ / ____________r branches to route messages per host.
            [_____lr_____<@test>(SkipName: @"Attribute$")]
            struct Start { }
        }

        // ═════════════════════════ MAVLink metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants
        // attached to the field, so units, invalid markers, display hints etc. stay available at runtime.
        // They must live inside the project interface (the agent expects every class in a project); the
        // connection's branch excludes them from its pack scope with SkipName.

        /** SI unit of a numeric field (a SI_Unit constant). */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** Value (or, for arrays, the [value] / [value:] / [v1,,v3,] notation) that marks the field as not set. */
        public class InvalidAttribute : Attribute { public InvalidAttribute(string value) { } }

        /** The field identifies the sensor / battery instance the message is about. */
        public class InstanceAttribute : Attribute { }

        /** UI hint, e.g. "bitmask": show the enum values as check boxes. */
        public class DisplayAttribute : Attribute { public DisplayAttribute(string hint) { } }

        /** printf-style display format. */
        public class PrintFormatAttribute : Attribute { public PrintFormatAttribute(string format) { } }

        /** Default value of the field. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** Scale factor: actual value = stated value * multiplier. */
        public class MultiplierAttribute : Attribute { public MultiplierAttribute(string factor) { } }

        /** Minimum value hint for UIs (not a wire constraint: [Invalid] markers may lie outside it). */
        public class MinValueAttribute : Attribute { public MinValueAttribute(double value) { } public MinValueAttribute(string value) { } }

        /** Maximum value hint for UIs (not a wire constraint: [Invalid] markers may lie outside it). */
        public class MaxValueAttribute : Attribute { public MaxValueAttribute(double value) { } public MaxValueAttribute(string value) { } }

        /** Declared after the &lt;extensions/&gt; marker: present in MAVLink 2 frames only. */
        public class ExtensionFieldAttribute : Attribute { }
    }
}
